[package]
name = "hycel-demo"
description = "Headless starter demo for the Hycel game engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hycel-core = { path = "../hycel-core", version = "0.1.0" }

[dev-dependencies]
hycel-assets = { path = "../hycel-assets", version = "0.1.0" }
hycel-input = { path = "../hycel-input", version = "0.1.0" }
hycel-project = { path = "../hycel-project", version = "0.1.0" }

[lints]
workspace = true
